### ISSUE TITLE
配置daed之後，無法訪問谷歌，但是youtube、facebook等網站沒有問題

### ISSUE THREAD

**Issue by wugeer** [daeuniverse/daed#134]
## What happened
google不能訪問
![image](https://github.com/daeuniverse/daed/assets/20339490/5595fc2d-f0b8-4a3b-864e-5b959a4c4366)
youtube可以
![image](https://github.com/daeuniverse/daed/assets/20339490/6786b004-04d2-43e1-9946-928abc9c0648)

## What you expect to happen
預期是谷歌搜索也可以訪問

## How to reproduce it (as minimally and precisely as possible):
daed的界面中，全局配置保持默認
dns配置頁面如下
![image](https://github.com/daeuniverse/daed/assets/20339490/94e6ac19-b912-4cfe-a35c-1952e0b15420)
路由配置如下
![image](https://github.com/daeuniverse/daed/assets/20339490/c2a82927-bb78-4abe-a6eb-f643107c1697)
代理節點配置爲
![image](https://github.com/daeuniverse/daed/assets/20339490/b11d68aa-1612-4c9c-87f0-f5554e8de81a)
daed的日誌
![image](https://github.com/daeuniverse/daed/assets/20339490/843571b0-aaff-4e98-a17b-c77ed9751b49)
xray的日誌
![image](https://github.com/daeuniverse/daed/assets/20339490/9bcf1e9c-398f-4a79-bc3e-2d3cee1c427a)

## Environment

- daed version (use `daed --version`): unstable-0.1.0rc.r49.g6f9b1b8
- OS (e.g `cat /etc/os-release`): CachyOS Linux IMAGE_VERSION:2023.04.23
- Kernel (e.g. `uname -a`): 6.4.2-1-cachyos
- Others: 
![image](https://github.com/daeuniverse/daed/assets/20339490/09d03621-9bff-42c1-bd2a-fc945b98e0a1)

❯ cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 192.168.3.1

其中nameserver 223.5.5.5和119.29.29.29都是一樣的結果

非常感謝各位大佬的幫助！！！！

**Comment by mzz2017** [comment]
我没有看到 google.com 的日志，将 dial_mode 改为 domain++ 再试试？

**Comment by wugeer** [comment]
> 我没有看到 google.com 的日志，将 dial_mode 改为 domain++ 再试试？

大佬好，我按照了domain++之後
![image](https://github.com/daeuniverse/daed/assets/20339490/9329626a-327c-471e-aeca-dcb0c3a0310a)
日誌如下
![image](https://github.com/daeuniverse/daed/assets/20339490/a786a52f-119b-4530-9ae2-44a5b2ca5f1b)

**Comment by mzz2017** [comment]
你可以 curl google.com -v 吗，这样日志条目比较清晰一些，看看 curl 会不会有正确返回，以及日志有没有对应输出。

**Comment by wugeer** [comment]
> curl google.com -v

你好，日誌輸出如下
❯ curl google.com -v 
*   Trying 172.217.163.46:80...
* Connected to google.com (172.217.163.46) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-42zw8k_eh7UxnIB97TFQLQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
< Date: Sun, 09 Jul 2023 03:09:30 GMT
< Expires: Tue, 08 Aug 2023 03:09:30 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
* Connection #0 to host google.com left intact

此時journalctl -exfu daed的輸出如圖所示
![image](https://github.com/daeuniverse/daed/assets/20339490/8becc995-37d9-46ac-ac6e-01545ca3a98c)

**Comment by mzz2017** [comment]
@wugeer 看起来是没什么问题的，curl 能正常访问

**Comment by wugeer** [comment]
> @wugeer 看起来是没什么问题的，curl 能正常访问

唉，但现在访问谷歌搜索一直不行，使用谷歌浏览器和火狐浏览器来访问这个地址都是不行的，而且我另外一台cachyos gnome是没问题的，我现在没有排查思路了，原先用的是dae也是不行的，arch的包都试过了，不行，源码编译的方式也试过了，也一样的结果

**Comment by mzz2017** [comment]
> 唉，但现在访问谷歌搜索一直不行，使用谷歌浏览器和火狐浏览器来访问这个地址都是不行的，而且我另外一台cachyos gnome是没问题的，我现在没有排查思路了，原先用的是dae也是不行的，arch的包都试过了，不行，源码编译的方式也试过了，也一样的结果

有可能你的客户机 dhcp 发的 dns 是一个内网地址，且不是 dae 所在机器，这样 dns 可能不经过 dae，导致了 dns 污染。

你可以将 dhcp 的 dns 地址发到一个公共 dns（例如 223.5.5.5），这样 dns 可以被 dae 拦截，并且防治污染。

**Comment by wugeer** [comment]
> > 唉，但现在访问谷歌搜索一直不行，使用谷歌浏览器和火狐浏览器来访问这个地址都是不行的，而且我另外一台cachyos gnome是没问题的，我现在没有排查思路了，原先用的是dae也是不行的，arch的包都试过了，不行，源码编译的方式也试过了，也一样的结果
> 
> 有可能你的 dhcp 给客户机发的 dns 是一个内网地址，且不是 dae 所在机器，这样 dns 可能不经过 dae，导致了 dns 污染。
> 
> 你可以将 dhcp 的 dns 地址发到一个公共 dns（例如 223.5.5.5），这样 dns 可以被 dae 拦截，并且防治污染。

這個也試過的，223.5.5.5和119.29.29.29都不行的，而且我換成了Proxy SwitchyOmega就可以了，google和youtube等都是可以正常訪問，所以感覺還是有點問題
![image](https://github.com/daeuniverse/daed/assets/20339490/1c253605-4ab6-45df-bb02-f65c51ac6b2f)
![image](https://github.com/daeuniverse/daed/assets/20339490/d88df344-e5a8-413a-9c0f-a1e22d5bf73d)

**Comment by mzz2017** [comment]
@wugeer switchyomega要怎么填？

**Comment by wugeer** [comment]
> @wugeer switchyomega要怎么填？

大佬好，我的switchyomega的配置如下
![image](https://github.com/daeuniverse/daed/assets/20339490/44f0f3b5-de1c-4602-bfe0-de5b1309db8a)
![image](https://github.com/daeuniverse/daed/assets/20339490/acb78d1c-f807-45c2-8c4d-fbf45aa30d7c)
谷歌是可用的
![image](https://github.com/daeuniverse/daed/assets/20339490/e320716f-2699-42e0-92d3-bff66deb9c1d)

**Comment by MarksonHon** [comment]
127.0.0.1:10808啊，这应该是v2rayN默认的socks入口，dae作为ebpf的代理工具是没有提供socks入口的

**Comment by wugeer** [comment]
> 这会导致，当你的 dns 受到污染，被解析到了一个本地地址，那么后续连接是不会往 dae 发的，就会出现你现在看到的这个问题。 你可以在客户机查询一下 google.com 的 dns 解析，应该会返回 127.0.0.1 或者 0.0.0.0。

dig google.com的結果
![image](https://github.com/daeuniverse/daed/assets/20339490/8b96ee31-5f8d-4707-9042-5a3b77466c76)

**Comment by mzz2017** [comment]
> > 这会导致，当你的 dns 受到污染，被解析到了一个本地地址，那么后续连接是不会往 dae 发的，就会出现你现在看到的这个问题。 你可以在客户机查询一下 google.com 的 dns 解析，应该会返回 127.0.0.1 或者 0.0.0.0。
> 
> dig google.com的結果 ![image](https://user-images.githubusercontent.com/20339490/253311215-8b96ee31-5f8d-4707-9042-5a3b77466c76.png)

看起来 dns 未经过 dae。你的 dhcp 未下发正确的 dns，请下发 223.5.5.5。

**Comment by kunish** [comment]
这个 issue 是不是已经解决了，那我先 close 了哈，有问题随时提

**Comment by Mapleshade20** [comment]
这个解决办法真的很有用！我bing一直被重定向到cnbing，改了dns route也没用，这才发现原来是没有在lan里指定dns。
可以参照这篇文章设置 https://www.cnblogs.com/NueXini/p/15703231.html
