### ISSUE TITLE
[Bug Report] mac地址代理白名单时无法正常 block 一个域名

### ISSUE THREAD

**Issue by douglarek** [daeuniverse/daed#230]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

我当前的路由配置：

```
pname(NetworkManager, systemd-resolved) -> direct

# miwifi
domain(full:api.miwifi.com)	-> block

# only proxy these devices
!mac('a')	-> direct(must)

dip(geoip:cn, geoip:private) -> direct
domain(geosite:cn) -> direct

fallback: proxy
```

按上面的设置，除了我 mac 地址为 `a` 的设备都能被代理，而不管设备有没有被代理它都应该不能访问 `api.miwifi.com`，但实际是在 b 电脑上依然能访问这个地址。

### Expected Behavior

如果规则是按顺序执行，那么在所有设备上都不应该能访问 `api.miwifi.com`。

### Environment

- **Daed version**:
0.3.2
- **OS (e.g `cat /etc/os-release`)**:
imm 23.05
- **Kernel (e.g. `uname -a`)**:
5.15.123
- **Others**:

**Comment by mzz2017** [comment]
@douglarek 正常，因为你的dns流量因为“must”而直连了，dae依靠dns来做分流

**Comment by mzz2017** [comment]
@douglarek 你的dns查询又不是domain，肯定match下面这一条mac的啊

**Comment by mzz2017** [comment]
@douglarek 哪里有dns回环？

**Comment by mzz2017** [comment]
@douglarek 你不要先下结论是dns回环，这个问题的根本原因到底是不是回环，要先从日志里找证据

**Comment by mzz2017** [comment]
@douglarek dns问题，上游是谁，拓扑怎么样，先画一下

**Comment by mzz2017** [comment]
@douglarek 发的dhcp网关和dns是谁

**Comment by mzz2017** [comment]
@douglarek 没有其他日志吗，这个日志没有什么用

**Comment by mzz2017** [comment]
@douglarek 不如在 dae 机器上 tcpdump 抓下包？连 25 Bytes 都没有

**Comment by mzz2017** [comment]
daed 开了 trace 日志吗？日志太少了

**Comment by mzz2017** [comment]
另外，你的daed机器上是不是有其他程序在53端口在监听？

**Comment by st0nie** [comment]
> 应该是 dnsmasq。但我理解这个影响吗，我是 pppoe 拨号的 wan，这个不会被代理吧。

试试先把 dnsmasq 的监听 53 停掉。然后 dhcp 服务器（在你的情况应该也是 dnsmasq）分发个 223.5.5.5

**Comment by mzz2017** [comment]
@st0nie 影响的，因为 dnsmasq 监听 any:53，导致 dae 劫持 dns 后无法绑定 223.5.5.5:53 进行回包，见置顶  issue

**Comment by YYiiEt** [comment]
之前同样遇到了由dnsmsaq导致的类似问题，貌似直接发公共dns加关掉劫持就好了
```
uci -q batch << EOF
set dhcp.@dnsmasq[0].dns_redirect='0'
delete dhcp.lan.dns
delete dhcp.lan.dhcp_option
add_list dhcp.lan.dns='2400:3200::1'
add_list dhcp.lan.dhcp_option='6,223.5.5.5'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart
```

**Comment by douglarek** [comment]
> 之前同样遇到了由dnsmsaq导致的类似问题，貌似直接发公共dns加关掉劫持就好了
> 
> ```
> uci -q batch << EOF
> set dhcp.@dnsmasq[0].dns_redirect='0'
> delete dhcp.lan.dns
> delete dhcp.lan.dhcp_option
> add_list dhcp.lan.dns='2400:3200::1'
> add_list dhcp.lan.dhcp_option='6,223.5.5.5'
> EOF
> uci commit dhcp
> /etc/init.d/dnsmasq restart
> ```

I have already tested this script, and it works like magic. I'm now going to close this issue unless the problem resurfaces. Thank you all for your contributions.
