### ISSUE TITLE
[Bug Report] refuse to start

### ISSUE THREAD

**Issue by hero-intelligent** [daeuniverse/daed#262]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

```
failed to load new config: ApplyRulesOptimizers error: geoip.dat: file does not exist in [/etc/daed, /root/.local/share/dae-wing, /usr/local/share/dae-wing, /usr/share/dae-wing]; see more in log
```

### Expected Behavior

just RUN!

### Environment

Docker

### Anything else?

I'll make a pull request to fix it.

**Comment by mzz2017** [comment]
@hero-intelligent How do you install it?

**Comment by hero-intelligent** [comment]
> @hero-intelligent How do you install it?

Docker. I'm working on it. almost done.

**Comment by mzz2017** [comment]
@hero-intelligent It is because APPNAME is not given in the building command.

**Comment by hero-intelligent** [comment]
This issue can be closed.
