### ISSUE TITLE
[Feature Request] 增加端口分享的功能

### ISSUE THREAD

**Issue by kyleli666** [daeuniverse/daed#307]
### Feature Request

由于我需要同时使用透明代理+端口分享，所以希望能增加与v2rayA一样的端口分享的功能。

目前我只能同时开着daed和v2rayA，daed做透明代理，v2rayA仅开启端口分享，但这样我需要同时维护两套rules，比较麻烦。

### Use Cases

同时使用透明代理+端口代理的场合

### Potential Benefits

可以完全替代v2rayA

**Comment by mzz2017** [comment]
@kyleli666 什么意思，这个是默认开的

**Comment by kyleli666** [comment]
related to https://github.com/daeuniverse/dae/issues/342
work around by using [glider](https://github.com/nadoo/glider)
