### ISSUE TITLE
[Bug Report] docker daed可以启动但无法运行

### ISSUE THREAD

**Issue by ReddotCleaner** [daeuniverse/daed#358]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

docker daed可以启动，但无法运行

### Expected Behavior

运行时提示
```failed to load new config: ApplyRulesOptimizers error: geosite.dat: file does not exist in [/etc/daed, /root/.local/share/dae-wing, /usr/local/share/dae-wing, /usr/share/dae-wing]; see more in log ```

### Steps to Reproduce

启动后点击运行

### Environment

- **Daed version**:  ```~ # daed -v
dae-wing version 0.0.0.unknown (docker中执行的结果)```
- **OS (e.g `cat /etc/os-release`)**:  debian 12
- **Kernel (e.g. `uname -a`)**: Linux debian 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

- **Others**:

**Comment by EkkoG** [comment]
daed 运行需要本地 geosite 和 geoip 数据库准备就绪，按照提示将 geosite.dat 和 geoip.dat 下载到对应位置即可

**Comment by ReddotCleaner** [comment]
> daed 运行需要本地 geosite 和 geoip 数据库准备就绪，按照提示将 geosite.dat 和 geoip.dat 下载到对应位置即可

感谢解答，我看了日志只下载了geoip，把geosite忘了🤣🤣
