### ISSUE TITLE
[Bug Report] 无法处理带有 `_` 的域名

### ISSUE THREAD

**Issue by merrkry** [daeuniverse/daed#430]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

报错如下：

```
DomainMatcher: skip bad suffix domain: *: unexpected chat: 95
```

相关规则在后续匹配中会被忽略。

### Expected Behavior

dae 应当在后续匹配中应用含 `_` 的规则。

### Steps to Reproduce

有如下规则：

```
domain(suffix: a_b.domain.tld) -> direct
fallback: proxy
```

报错：

```
DomainMatcher: skip bad suffix domain: a_b.domain.tld: unexpected chat: 95
```

分析日志发现 a_b.domain.tld 从 proxy 拨号。

### Environment

- **Daed version**: `v0.4.0rc1`
- **OS (e.g `cat /etc/os-release`)**: `Arch Linux`
- **Kernel (e.g. `uname -a`)**: `6.8.6-2-cachyos-lto`
- **Others**:

### Anything else?

域名/主机名中关于下划线的规定比较复杂。实践中也常常有非标准的做法。实际上，Cloudflare 控制台也允许创建诸如 `_a_b_c_.domain.tld` 的 DNS 记录。

从兼容性考虑，dae 应当允许此类域名参与路由。

**Comment by wanlce** [comment]
@merrkry 
https://github.com/daeuniverse/daed/actions/runs/8214056539

**Comment by merrkry** [comment]
> @merrkry https://github.com/daeuniverse/daed/actions/runs/8214056539

感谢。

在 `archlinuxcn/daed-git`，版本 `0.4.0rc1.r68.g2841ec2-3` 已经能够处理下划线。
