### ISSUE TITLE
[Bug Report] daed的路由填写似乎不接受IPv6地址/CIDR

### ISSUE THREAD

**Issue by Glucy-2** [daeuniverse/daed#434]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

在 daed 中填写路由时，如果 `sip` 或 `dip` 中包含 IPv6 地址 / CIDR，则 daed 会拒绝此规则

### Expected Behavior

daed 能够正常设置 IPv6 路由

### Steps to Reproduce

1. 安装并启动 daed
2. 在路由中填写包含 IPv6 地址 / CIDR 的路由规则，例如如下规则：
```
dip(2001:da8::/32) -> direct
```
会报错：
```
bad current routing: 
line 30:8 dip(2001:da8::/32) -> direct
                  ^: no viable alternative at input 'dip(2001:'
```
如果填写：
```
dip('2001:da8::/32') -> direct
```
会报错：
```
panic occurred: unexpected
```

### Environment

- **Daed version**: v0.4.1
- **OS (e.g `cat /etc/os-release`)**: PVE (基于 Debian 12)
- **Kernel (e.g. `uname -a`)**: `6.8.4-2-pve`
- **Others**: NA

**Comment by EkkoG** [comment]
麻烦尝试一下最新版，我这边没有复现这个问题

**Comment by mzz2017** [comment]
这个写的时候要加引号
