### ISSUE TITLE
[Bug Report] Openwrt下局域网其它设备可代理，本机只能直出

### ISSUE THREAD

**Issue by cantona97** [daeuniverse/daed#454]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

两台x86的openwrt路由器（eth0通过pppoe拨号上网），安装daed后局域网的所有设备都能按规则分流，唯独本机只能直出（通过curl等测试）。
"wanInterface"在页面中只能选择“Auto”或者“pppoe-wan”，尝试过手工在"wanInterface"添加了eth0(nano /etc/daed/wing.db)，但设置后daed就不能正常启动。执行ip a命令，pppoe的虚拟网卡的state是“UNKNOWN”，不知是否和这个有关，但连接互联网是正常的。我的配置文件如下：
{
  "id": "xxxxxx",
  "name": "global",
  "selected": true,
  "global": {
    "logLevel": "info",
    "tproxyPort": 12345,
    "allowInsecure": false,
    "checkInterval": "1m0s",
    "checkTolerance": "200ms",
    "lanInterface": [
      "br-lan"
    ],
    "wanInterface": [
      "auto",
      "pppoe-wan"
    ],
    "udpCheckDns": [
      "dns.google.com:53",
      "8.8.8.8",
      "2001:4860:4860::8888"
    ],
    "tcpCheckUrl": [
      "http://cp.cloudflare.com",
      "1.1.1.1",
      "2606:4700:4700::1111"
    ],
    "dialMode": "domain",
    "tcpCheckHttpMethod": "HEAD",
    "disableWaitingNetwork": false,
    "autoConfigKernelParameter": true,
    "sniffingTimeout": "100ms",
    "tlsImplementation": "tls",
    "utlsImitate": "chrome_auto",
    "tproxyPortProtect": true,
    "soMarkFromDae": 0
  }
}

************************************
补充：
在另外一台openwrt的路由器中，因为联网方式是DHCP，所以 "wanInterface"可选择“Auto”和“eth0”，这台路由器就可以经daed访问外网，配置和上面的一样，唯一区别就是"wanInterface"是“eth0”，这三台路由器的软硬件配置都一样，唯一的区别就是联网方式。不知道这是软件的bug还是我的配置有问题，希望大神能指点一下，非常感谢！

### Environment

- **Daed version*：0.60*:
- **OS (e.g `cat /etc/os-release`)*：Openwrt*:
- **Kernel (e.g. `uname -a`)*：Linux 5.15.155  x86_64 GNU/Linux*:
- **Others**:

**Comment by github-xihe** [comment]
dae不支持pppoe本机代理

**Comment by cantona97** [comment]
> dae不支持pppoe本机代理

谢谢！如果是这样的话，是否支持在dae的设置中添加一个socks代理入站呢，起码我可以用curl --proxy socks://127.0.0.1:1080之类临时使用代理了

**Comment by github-xihe** [comment]
> > dae不支持pppoe本机代理
> 
> 噢！我在dae的troubleshooting看到了dae是不支持pppoe的，谢谢！ 除了 [daeuniverse/dae#304](https://github.com/daeuniverse/dae/discussions/304) 所描述的方式（我觉得复杂了点）外，是否支持在dae的设置中添加一个socks代理入站呢，起码我可以用curl --proxy socks://127.0.0.1:1080之类临时使用代理了

不可以，如果想临时使用代理，可以用gg[https://github.com/mzz2017/gg](url)

**Comment by kennysoul** [comment]
> > > dae不支持pppoe本机代理
> > 
> > 
> > 噢！我在dae的troubleshooting看到了dae是不支持pppoe的，谢谢！ 除了 [daeuniverse/dae#304](https://github.com/daeuniverse/dae/discussions/304) 所描述的方式（我觉得复杂了点）外，是否支持在dae的设置中添加一个socks代理入站呢，起码我可以用curl --proxy socks://127.0.0.1:1080之类临时使用代理了
> 
> 不可以，如果想临时使用代理，可以用[gg](https://github.com/mzz2017/gg)

受教了，谢谢！

**Comment by ash0080** [comment]
> > > dae不支持pppoe本机代理
> > 
> > 
> > 噢！我在dae的troubleshooting看到了dae是不支持pppoe的，谢谢！ 除了 [daeuniverse/dae#304](https://github.com/daeuniverse/dae/discussions/304) 所描述的方式（我觉得复杂了点）外，是否支持在dae的设置中添加一个socks代理入站呢，起码我可以用curl --proxy socks://127.0.0.1:1080之类临时使用代理了
> 
> 不可以，如果想临时使用代理，可以用[gg](https://github.com/mzz2017/gg)

我也发现了这个问题, 我想请问下, 是不是能理解为dae现在完全不支持localhost走代理? 那目前有两个很现实的问题,一个是localhost安装软件需要走代理,还有就是docker容器需要走代理, 这两种情况, 目前有可行的解决方案么?

**Comment by wanlce** [comment]
@ash0080 只是不支持 PPPoE ，如果想弄的话可以参考下面的文档
[Proxy WAN interface with PPPoE type](https://github.com/daeuniverse/dae/discussions/304)

**Comment by ash0080** [comment]
> @ash0080 只是不支持 PPPoE ，如果想弄的话可以参考下面的文档 [Proxy WAN interface with PPPoE type](https://github.com/daeuniverse/dae/discussions/304)

我尝试了一下没有成功,操作如下 [括号内是不成功又尝试的其他操作]
1.修改了global两项 [尝试添加了lo到lan interface]
2.nftables里添加了inet dae-wan, 先没动iptables, 因为是23.05,不依赖iptables,默认是nftables
3.reload daed

ssh到immortWrt, curl -i google 没响应

有几个问题
1. ip和nft必须同时修改么? 我知道dockerd走iptables,但我暂时没测docker容器
2. daed这边还需不要一些额外的设置,比如修改interface绑定? 或者是否需要在dns里添加l4proto(tcp)之类的? 因为现在nslookup看上去localhost的dns也都没有经过dae,仍然是走的127.0.0.1:53
3. 以上带来一个新问题, dnsmasq需要修改么?

**Comment by mzz2017** [comment]
@ash0080 可以尝试 0.5.1，后续版本这个功能行为猜测有些变化
