### ISSUE TITLE
基本硬件：树莓派4B，安装ubuntu 24.04服务器版本，使用daed的armv7版本,我在使用daed项目时，提示nanotime returning zero

### ISSUE THREAD

**Issue by hedove** [daeuniverse/daed#455]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

基本硬件：树莓派4B，安装ubuntu 24.04服务器版本，使用daed的armv7版本,我在使用daed项目时，提示这个，
root@raspberrypi:/opt/daed# systemctl status daed.service
× daed.service - daed is a integration solution of dae, API and UI.
     Loaded: loaded (/etc/systemd/system/daed.service; disabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2024-06-30 22:21:35 CST; 6min ago
   Duration: 3min 39.231s
       Docs: https://github.com/daeuniverse/daed
    Process: 15591 ExecStart=/opt/daed/daed run -c /opt/daed/ (code=exited, status=2)
   Main PID: 15591 (code=exited, status=2)
        CPU: 7min 18.219s

Jun 30 22:21:33 raspberrypi daed[15591]: goroutine 1 gp=0x2c02128 m=0 mp=0x21373c0 [running, locked to thread]:
Jun 30 22:21:35 raspberrypi daed[15591]: runtime.throw({0x101d096, 0x17})
Jun 30 22:21:35 raspberrypi daed[15591]:         runtime/panic.go:1023 +0x4c fp=0x2c567a8 sp=0x2c56794 pc=0x52cec
Jun 30 22:21:35 raspberrypi daed[15591]: runtime.main()
Jun 30 22:21:35 raspberrypi daed[15591]:         runtime/proc.go:192 +0x4a4 fp=0x2c567ec sp=0x2c567a8 pc=0x561ec
Jun 30 22:21:35 raspberrypi daed[15591]: runtime.goexit({})
Jun 30 22:21:35 raspberrypi daed[15591]:         runtime/asm_arm.s:859 +0x4 fp=0x2c567ec sp=0x2c567ec pc=0x8df20
Jun 30 22:21:35 raspberrypi systemd[1]: daed.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 30 22:21:35 raspberrypi systemd[1]: daed.service: Failed with result 'exit-code'.
Jun 30 22:21:35 raspberrypi systemd[1]: daed.service: Consumed 7min 18.219s CPU time, 960.0K memory peak, 0B memory swa>
 ESCOC
and UI.
led; preset: enabled)
 22:21:35 CST; 6min ago

/ (code=exited, status=2)

02128 m=0 mp=0x21373c0 [running, locked to thread]:
1d096, 0x17})
ic.go:1023 +0x4c fp=0x2c567a8 sp=0x2c56794 pc=0x52cec

c.go:192 +0x4a4 fp=0x2c567ec sp=0x2c567a8 pc=0x561ec

_arm.s:859 +0x4 fp=0x2c567ec sp=0x2c567ec pc=0x8df20
rocess exited, code=exited, status=2/INVALIDARGUMENT
 with result 'exit-code'.
ed 7min 18.219s CPU time, 960.0K memory peak, 0B memory swap peak.

不知道是不是兼容性的问题。

### Environment

- **Daed version**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

### Anything else?

无

**Comment by mzz2017** [comment]
journalctl -b -u daed -o cat

**Comment by hedove** [comment]
> journalctl -b -u daed -o cat

root@raspberrypi:/opt/daed# journalctl -b -u daed -o cat
root@raspberrypi:/opt/daed# /opt/daed/daed run -c /opt/daed/
fatal error: 
^Cnanotime returning zero

goroutine 1 gp=0x3802128 m=0 mp=0x21373c0 [running, locked to thread
root@raspberrypi:/opt/daed# journalctl -b -u daed -o cat      




nothing else.

**Comment by hedove** [comment]
root@raspberrypi:/opt/daed# systemctl status daed.service
● daed.service - daed is a integration solution of dae, API and UI.
     Loaded: loaded (/etc/systemd/system/daed.service; disabled; preset: enabled)
     Active: active (running) since Mon 2024-07-01 00:09:17 CST; 2s ago
       Docs: https://github.com/daeuniverse/daed
   Main PID: 1327 (daed)
      Tasks: 2 (limit: 8686)
     Memory: 492.0K (peak: 948.0K)
        CPU: 5.015s
     CGroup: /system.slice/daed.service
             └─1327 /opt/daed/daed run -c /opt/daed/

Jul 01 00:09:17 raspberrypi systemd[1]: Started daed.service - daed is a integration solution of dae, API and UI..
Jul 01 00:09:17 raspberrypi daed[1327]: fatal error: nanotime returning zero           

nanotime returning zero.that's all.

**Comment by MarksonHon** [comment]
@hedove Please send us detailed information about your system version and CPU architecture.

**Comment by mzz2017** [comment]
树莓派4B是arm64的，你下载armv7的daed使用可能会有问题

**Comment by hedove** [comment]
root@raspberrypi:/opt/daed# uname -r
6.8.0-1004-raspi
root@raspberrypi:/opt/daed# (zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}) | grep -E 'CONFIG_(DEBUG_INFO|DEBUG_INFO_BTF|KPROBES|KPROBE_EVENTS|BPF|BPF_SYSCALL|BPF_JIT|BPF_STREAM_PARSER|NET_CLS_ACT|NET_SCH_INGRESS|NET_INGRESS|NET_EGRESS|NET_CLS_BPF|BPF_EVENTS|CGROUPS)=|# CONFIG_DEBUG_INFO_REDUCED is not set'
gzip: /proc/config.gz: No such file or directory
cat: /boot/config: No such file or directory
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_CGROUPS=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_INFO_REDUCED is not set
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y

> 树莓派4B是arm64，你下载的armv7的daed使用可能会有问题，
> 
> uname -a

似乎是没有CONFIG_DEBUG_INFO_BTF=y  这一项吗？  我看到官方要求的内核是需要开启这一项，如果是树莓派需要如何开启它呢？

**Comment by hedove** [comment]
> @hedove请您发送有关您的系统版本和 CPU 架构的详细信息。

root@raspberrypi:/opt/daed# uname -r
6.8.0-1004-raspi
root@raspberrypi:/opt/daed# (zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}) | grep -E 'CONFIG_(DEBUG_INFO|DEBUG_INFO_BTF|KPROBES|KPROBE_EVENTS|BPF|BPF_SYSCALL|BPF_JIT|BPF_STREAM_PARSER|NET_CLS_ACT|NET_SCH_INGRESS|NET_INGRESS|NET_EGRESS|NET_CLS_BPF|BPF_EVENTS|CGROUPS)=|# CONFIG_DEBUG_INFO_REDUCED 未设置'
gzip：/proc/config.gz：没有此文件或目录
cat：/boot/config：没有此文件或目录
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_CGROUPS=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_DEBUG_INFO=y

#CONFIG_DEBUG_INFO_REDUCED
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y

树莓派4B是arm64，你下载的armv7的daed使用可能会有问题，

uname -a

似乎没有 CONFIG_DEBUG_INFO_BTF=y 这一项？ 看到官​​方要求的内核是需要开启这一项，如果是树莓需要如何开启它呢？

**Comment by hedove** [comment]
我更换了arm64版本依然无法运行。

**Comment by mzz2017** [comment]
1. 你的操作系统要选 arm64(aarch64)
1. 你需要重新编译内核以加入 btf 支持
1. “依然无法运行”没有任何日志反馈
