### ISSUE TITLE
如何用daed 导出config ，我希望用daed 导出，然后永远不用daed,而是使用dae

### ISSUE THREAD

**Issue by slociv** [daeuniverse/daed#460]

**Comment by MarksonHon** [comment]
Use `daed export`

**Comment by mzz2017** [comment]
@slociv 开 trace 会打印 config

**Comment by lixin-wei** [comment]
@MarksonHon 大佬问下怎么daed export怎么导出配置呀？我试了 --help里说的 `flatdesc`, `outline`, `schema`好像都不是配置诶

**Comment by wanlce** [comment]
@lixin-wei 没这个，web页面点小眼睛图标查看吧

**Comment by lixin-wei** [comment]
@wanlce 感谢回复，小眼睛好像只能看DNS/Route，看不了Group诶，group上面没有小眼睛。我想导出group的配置要怎么做呢？
