### ISSUE TITLE
希望在WEBUI添加特定域名不走代理的管理功能,有一些域名虽然是国外但是没被禁用,代理后反而会出问题

### ISSUE THREAD

**Issue by ray154856235** [daeuniverse/daed#461]
### Feature Request

希望在WEBUI添加特定域名不走代理的管理功能,有一些域名虽然是国外但是没被禁用,代理后反而会出问题

**Comment by MarksonHon** [comment]
You should write RoutingA rules according the [dae wiki](https://github.com/daeuniverse/dae/tree/main/docs) by yourself, it is a existing feature already.
