### ISSUE TITLE
group proxy 不支持 fixed(0) 

### ISSUE THREAD

**Issue by loverainye** [daeuniverse/daed#466]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

我有一个订阅关联 my_proxy group，一个node socks5代理关联 my_node group, 现在daed中的群组 policy 不支持 fixed(0），导致匹配到node的时候，有时可用有时不可用。用dae配置fixed(0) 正常
日志信息 443: failed to select dialer from group my_node (tcp6): no alive dialer

### Expected Behavior

daed中支持 fixed(0)

### Environment

- **Daed version**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by wanlce** [comment]
@loverainye 试试这个 https://github.com/daeuniverse/daed/actions/runs/10011018084

**Comment by wanlce** [comment]
@loverainye 试试这个 https://github.com/daeuniverse/daed/actions/runs/10011018084

**Comment by QiuSimons** [comment]
用最新的commit编译出来依然没看到fixed选项

![image](https://github.com/user-attachments/assets/ef9cd658-f0cd-4f8d-98db-081803e7755f)

**Comment by wanlce** [comment]
@QiuSimons 你这是诈骗呀 :smiley:
[v0.7.0](https://github.com/daeuniverse/daed/releases/tag/v0.7.0) 里是没有 fixed(0) 的
![image](https://github.com/user-attachments/assets/646c11a4-95bf-41a2-bcb3-dd974ac63d0a)

**Comment by QiuSimons** [comment]
> @QiuSimons 你这是诈骗呀 😃 [v0.7.0](https://github.com/daeuniverse/daed/releases/tag/v0.7.0) 里是没有 fixed(0) 的 ![image](https://private-user-images.githubusercontent.com/55907021/355450389-646c11a4-95bf-41a2-bcb3-dd974ac63d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODcwMDMsIm5iZiI6MTcyMjk4NjcwMywicGF0aCI6Ii81NTkwNzAyMS8zNTU0NTAzODktNjQ2YzExYTQtOTViZi00MWEyLWJjYjMtZGQ5NzRhYzYzZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDIzMjUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYmFhMzE4ZTBhZjQzODJlMTIxYWEwMzU3NjU4ZTA2YzIyMDFhMGVjZmNlOTNkZWRjODM3ZjJmNmJlNWExYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tt48gfAg3voKq1VhhNcArn3u7irlMDxmhGPbLB_c7os)

你看下面….有切最新commit操作的（

**Comment by QiuSimons** [comment]
> @QiuSimons 你这是诈骗呀 😃 [v0.7.0](https://github.com/daeuniverse/daed/releases/tag/v0.7.0) 里是没有 fixed(0) 的 ![image](https://private-user-images.githubusercontent.com/55907021/355450389-646c11a4-95bf-41a2-bcb3-dd974ac63d0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NzIyMTMsIm5iZiI6MTcyNzU3MTkxMywicGF0aCI6Ii81NTkwNzAyMS8zNTU0NTAzODktNjQ2YzExYTQtOTViZi00MWEyLWJjYjMtZGQ5NzRhYzYzZDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAxMDUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYjA2MmYyNWMzMjIwYzRlYmI2NzgwOWYwN2M4ODk4NDQ4ZDc3OWUwYjFiOWE5YTU1ODNiOTFkYWQ5MWYxMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jPGSDbizYAdeVewgRXgIxXrEz-dkr9NBrRyH9__h_Qs)

074好像还是没看到fixed

**Comment by wanlce** [comment]
@QiuSimons 是的，因为 daed 的 fixed 选项需要用到 https://github.com/daeuniverse/dae/pull/582 这个提交，而这个提交没有被合并到 dae 的 0.7.4 中，所以没办法添加（

**Comment by QiuSimons** [comment]
> @QiuSimons 是的，因为 daed 的 fixed 选项需要用到 [daeuniverse/dae#582](https://github.com/daeuniverse/dae/pull/582) 这个提交，而这个提交没有被合并到 dae 的 0.7.4 中，所以没办法添加（

但是我自己编译的daed用的其实是main 的dae当核心，所以daed这边其实需要开某个编译选项才能获得这个fixed么？还是说要直接编译main的daed配合main的wing main的core？
