### ISSUE TITLE
[Bug Report] dae更新后daed不正常

### ISSUE THREAD

**Issue by CodeIntegrity** [daeuniverse/daed#489]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

使用最新版本dae通过daed面板添加订阅节点会先报panic occurred: runtime error: invalid memory address or nil pointer dereference ，然后报database is locked (5) (SQLITE_BUSY)

### Environment

- **Daed version**:0.7.0
- **OS (e.g `cat /etc/os-release`)**:OpenWrt 23.05.4 r24012-d8dd03c46f
- **Kernel (e.g. `uname -a`)**:Linux OpenWrt 5.15.162 #0 SMP Mon Jul 15 22:14:18 2024 x86_64 GNU/Linux

**Comment by EkkoG** [comment]
请尝试 [0.8.0](https://github.com/daeuniverse/daed/releases/tag/v0.8.0) 或者 [0.7.4](https://github.com/daeuniverse/daed/releases/tag/v0.7.4) 问题修复在 https://github.com/daeuniverse/dae-wing/commit/25b949bc9a204d78abd12faade9b43aa8f4c8fb8 ，这两个版本包含这个修复

**Comment by wanlce** [comment]
已修复了
