### ISSUE TITLE
[Bug Report] docker镜像触发构建时机不正确

### ISSUE THREAD

**Issue by KagurazakaNyaa** [daeuniverse/daed#499]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

注意到 https://github.com/daeuniverse/daed/actions/workflows/publish-docker-image.yml 这里没有被 0.8.0 和 0.7.4 的release触发构建
参考 https://docs.github.com/zh/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release

### Expected Behavior

每次发布release都应当触发docker镜像构建和推送
https://github.com/daeuniverse/daed/blob/main/.github/workflows/publish-docker-image.yml#L9 这里应当是 `[published]` 而不是 `[prereleased,released]`

### Steps to Reproduce

检查 https://github.com/daeuniverse/daed/actions/workflows/publish-docker-image.yml ，和release发布对照

### Environment

N/A

**Comment by wanlce** [comment]
感谢报告，可以帮忙修改吗，谢谢！

**Comment by KagurazakaNyaa** [comment]
@wanlce 已经在pr中提交修改
