### ISSUE TITLE
[Bug Report] Flake breaks on latest NixOS unstable

### ISSUE THREAD

**Issue by iopq** [daeuniverse/daed#506]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

When enabling daed service:
```
error: lib.meta.getExe': The first argument is of type lambda, but it should be a derivation instead.
```

### Expected Behavior

it should work like before

### Steps to Reproduce

 in configuration.nix:
```
services.daed = true;
```

in flake.nix:

```
    daeuniverse.url = "github:daeuniverse/flake.nix";

...

modules = [

	inputs.daeuniverse.nixosModules.dae
	inputs.daeuniverse.nixosModules.daed

...
]
```

### Environment

- **Daed version**: 0.8.0
- **OS (e.g `cat /etc/os-release`)**:  
```
ANSI_COLOR="0;38;2;126;186;228"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="25.05.20241203.55d15ad"
CPE_NAME="cpe:/o:nixos:nixos:25.05"
DEFAULT_HOSTNAME=nixos
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 25.05 (Warbler)"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="25.05 (Warbler)"
VERSION_CODENAME=warbler
VERSION_ID="25.05"
```
- **Kernel (e.g. `uname -a`)**: `Linux desktop 6.6.63 #1-NixOS SMP PREEMPT_DYNAMIC Fri Nov 22 14:38:37 UTC 2024 x86_64 GNU/Linux`

- **Others**:

**Comment by oluceps** [comment]
Here had a [pr](https://github.com/daeuniverse/flake.nix/pull/131) fixed that but merging blocking since no code owner reviewed.

**Comment by oluceps** [comment]
Merged. Could you test if this is solved?

**Comment by iopq** [comment]
Solved by https://github.com/daeuniverse/flake.nix/pull/131
